### ISSUE TITLE
1808数据更新列表 ​

### ISSUE THREAD

**Issue by mic12130** [VATPRC-Sector/VATPRC-Sector-Project#43]
**Description**

节选自[2018年第8期NAIP修订信息简报](https://www.aischina.com/CN/News.aspx?id=6DEC8F204CF31910)>机场修订主要内容>特种航图。列表不包含导航数据的更改、非公开机场的更改和不涉及扇区的更改。

1、	华北地区：

- [x] 北京/首都: 机坪W5重新划分为W5、W6，增设PB点，M7滑延长。（issue #42）
~~呼和浩特/白塔：增设进近管制扇区。~~（已在1807的 #26 中更新）
- [x] 呼伦贝尔/海拉尔:新增D-ATIS。(issue #57)

2、	东北地区：

无

3、	华东地区：

- [x] 济南/遥墙：机场图、停机位置图新增放行频率（issue #50 )
- [x] 南通/兴东：取消901-905号停机位西侧滑行道L、更改901-905停机位坐标、滑行线、滑行道L。（issue #41）
- ~~温州/龙湾：新增滑行线、隔离机位。~~（暂时缺少新地景）

4、	中南地区：

- [x] 深圳/宝安：新增APP05。（issue #58）

5、	西南地区：

无

6、	西北地区：

无

7、	新疆:

无

**Screenshots**

**Comment by websterzh** [comment]
济南遥墙频率：1809统一更新

**Comment by mic12130** [comment]
1809里程碑下的两个席位和分扇更新不包括上海情报区啊…

**Comment by mic12130** [comment]
济南频率将在1808更新

**Comment by websterzh** [comment]
#55 中已经更新ZGJD_5_APP和ZBLA_ATIS频率，至于ZBHH_APP频率在上次更新中已经加入。

**Comment by mic12130** [comment]
Done
