### ISSUE TITLE
1810数据更新列表

### ISSUE THREAD

**Issue by mic12130** [VATPRC-Sector/VATPRC-Sector-Project#89]
**Description**

节选自[2018年第10期NAIP修订信息简报](https://www.aischina.com/CN/News.aspx?id=48C35F7858AD5BF6)中的航路修订主要内容以及机场修订主要内容>特种航图。列表不包含导航数据的更改、非公开机场的更改和不涉及扇区的更改。

航路修订主要内容：

- [x] 调整西宁进近01、02号扇区主频（ #45 ）
- [x] 调整上海进近管制区01、02、03、04、05、06、07、09、10号扇区，增设11号扇区（ #93 ）
- [x] 调整南京进近管制区04号扇区（ #94 ）

1、 华北地区：

- 天津/滨海：~~新增施工区域，部分停机位关闭~~（地景未更新）。

2、 东北地区：

- 哈尔滨/太平：~~撤销1-9、10-16号停机位，新增701-712临时停机位。~~（ #90 ，不再包含在1810更新中）
- 沈阳/桃仙：~~修改扇区频率。~~（ #46 ，不再包含在1810更新中）

3、 华东地区：

- [x] 上海/虹桥：停机位更名。（ #91 ）
- 烟台/蓬莱：~~新增停机位。~~（暂无匹配地景）

4、 中南地区：

- 桂林/两江：~~新增、删除停机位，停机坪重新命名。~~（暂无匹配地景）
- 珠海/金湾：~~新增DCL~~（ #80  ，不再包含在1810更新中）。
- [x] 海口/美兰：新增放行频率。（ #45 ）

5、西南地区：

- 成都/双流：~~新增滑行线、滑行等待位置。~~（暂无匹配地景）

6、西北地区：

无

7、新疆:

无

**Screenshots**
